services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend-flask/app:/app/app
    networks:
      - app-network
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: ../Dockerfile.frontend
    ports: 
      - "3000:5173"
    volumes:
      - ./frontend-svelte:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://192.168.68.200:4000
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge