services:
  tailscale:
    container_name: tailscaled
    image: tailscale/tailscale
    hostname: lessonorganizer
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale/varlib:/var/lib
      - ./tailscale/tmp:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - TAILSCALE_UP_ARGS=--snat-subnet-routes=false
      
  backend:
    volumes:
      - ./db_backups:/backup
    environment:
      - FLASK_ENV=production
    entrypoint: ["/bin/sh", "-c"]
    command: |
      cron && exec python app/main.py

  # caddy:
  #   image: caddy:latest
  #   container_name: caddy
  #   networks:
  #     - app-network
  #   ports:
  #     - "80:80"
  #     # - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - frontend
  #     - backend

networks:
  app-network:
    driver: bridge

# volumes:
#   caddy_data:
#   caddy_config: