services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend-flask/app:/app/app
    networks:
      - app-network
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: ../Dockerfile.frontend
    ports: 
      - "3000:5173"
    volumes:
      - ./frontend-svelte:/app
      - /app/node_modules
      - frontend-cache:/app/node_modules/.cache
    command: npm run dev
    networks:
      - app-network
    depends_on:
      - backend




networks:
  app-network:
    driver: bridge

volumes:
  frontend-cache:
  caddy_data:
  caddy_config: