services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend-flask:/app
      - backend_db:/app/instance
    networks:
      - app-network
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
      - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  frontend:
    build:
      context: ./frontend-svelte/
      dockerfile: Dockerfile.frontend
    ports: 
      - "3000:5173"
    volumes:
      - ./frontend-svelte:/app
      - node_modules:/app/node_modules
      - frontend-cache:/app/node_modules/.cache
    command: npm run dev
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}




networks:
  app-network:
    driver: bridge

volumes:
  backend_db:
  node_modules:
  frontend-cache:
  caddy_data:
  caddy_config: