services:
  backend:
    image: ghcr.io/elliot-ttge/lesson-organizer-backend:latest
    volumes:
      - backend_db:/app/instance
    networks:
      - app-network
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=production
      - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
      - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped

  frontend:
    image: ghcr.io/elliot-ttge/lesson-organizer-frontend:latest
    volumes:
      - frontend-cache:/app/node_modules/.cache
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  cron-backup:
    image: alpine:latest
    container_name: cron-backup
    volumes:
      - ./db_backups:/db_backups
      - backend_db:/db_source:ro
    entrypoint: |
      /bin/sh -c '
        echo "0 3 * * 0 cp /db_source/lesson_organizer.db /db_backups/backup-\$(date +\\%F_\\%H-\\%M-\\%S).db && find /db_backups -name \"backup-*.db\" -mtime +90 -delete" > /etc/crontabs/root
        crond -f -d 8
      '
    depends_on:
      - backend
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_db:
  frontend-cache:
  caddy_data:
  caddy_config:
