FROM python:3.12-slim

WORKDIR /app

COPY backend-flask/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY backend-flask /app

EXPOSE 4000

ENV FLASK_APP=app.main
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=4000

CMD ["flask", "run"]