Project lesson_organizer {
    database_type: 'SQLite'
}

Table student {
    id integer [pk, not null, unique, increment]
    name varchar [not null]
    created_date datetime [not null]
}

Table lesson {
    id integer [pk, not null, unique, increment]
    datetime datetime [not null]
    plan varchar [not null]
    concepts varchar [not null]
    created_date datetime [not null]
    notes varchar
}

Table quiz {
    id integer [pk, not null, unique, increment]
    name varchar [not null]
    datetime datetime [not null]
    score real [not null]
    notes varchar
    lesson_id integer [not null, ref: > lesson.id]
    student_id integer [not null, ref: > student.id]
}

Table lesson_student {
    id integer [pk, not null, unique, increment]
    lesson_id integer [not null, ref: > lesson.id]
    student_id integer [not null, ref: > student.id]
}

Table english_level {
    id integer [pk, not null, unique, increment]
    student_id integer [not null, ref: > student.id]
    start_date datetime [not null]
    level_category varchar [not null]
}

Table stock_image {
    id integer [pk, not null, unique, increment]
    istock_name varchar
    istock_id integer
    uses varchar
}

Table user {
    id integer [pk, not null, unique, increment]
    first_name varchar
    last_name varchar
    created_date datetime
    last_login datetime
    password varchar
    role_id integer [ref: > user_role.id]
}

Table user_role {
    id integer [pk, not null, unique, increment]
    role_name varchar
    created_date datetime
}

// Relationships
Ref: lesson.id > lesson_student.lesson_id
Ref: student.id > lesson_student.student_id
Ref: lesson.id > quiz.lesson_id
Ref: student.id > quiz.student_id
Ref: student.id > english_level.student_id
Ref: user_role.id > user.role_id
