FROM python:3.12-slim-bullseye

RUN apt update

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . /app/

COPY entrypoint.py /app/entrypoint.py

EXPOSE 4000

ENV FLASK_APP=app.main
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=4000

CMD ["sh", "-c", "python -u /app/entrypoint.py --load-init && gunicorn --bind 0.0.0.0:4000 --workers 4 --timeout 120 --access-logfile - --error-logfile - app.main:app"]
