"""Update permission_level enum from admin to manage

Revision ID: e4b1c0aa3c9c
Revises: a32b2b08f360
Create Date: 2025-10-16 23:29:33.676041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1c0aa3c9c'
down_revision = 'a32b2b08f360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson', schema=None) as batch_op:
        batch_op.alter_column('permission_level',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('view', 'edit', 'manage', name='permission_level'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson', schema=None) as batch_op:
        batch_op.alter_column('permission_level',
               existing_type=sa.Enum('view', 'edit', 'manage', name='permission_level'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
