name: CI

on:
    pull_request:

    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        #   - name: Build frontend
        #     run: |
        #       docker compose build frontend